### ISSUE TITLE
请教下关于中文翻译对照表

### ISSUE THREAD

**Issue by hnzxmutex** [lucifering/PoeModEn2CN#11]
萌新想请问下,中英对照表是哪里导出的呢?用poestrings一个一个对比?还是爬取poedb上面的数据呢?
比如这种翻译
`{"en":/This Attack and Minions deal (\d+|(\d+\.\d+))% more Damage with Hits and Ailments against Chilled Enemies/g,"cn":"此攻击与召唤生物攻击被冰缓的敌人时，击中和异常状态总伤害额外提高 #%"},`

**Comment by lucifering** [comment]
游戏文件 Content.ggpk 里面有 Metadata/StatDescriptions/（各种词缀）.txt 的文件，我导出后写了一个java的程序来解析这些txt文件，最终生成我需要的格式。

**Comment by hnzxmutex** [comment]
谢谢,非常感谢
