### ISSUE TITLE
poe.ninja上角色的有的药剂未汉化

### ISSUE THREAD

**Issue by monkey000** [lucifering/PoeModEn2CN#2]
![tim 20180607160123](https://user-images.githubusercontent.com/36021889/41086298-2f66c854-6a6c-11e8-8889-8a01bb41f5c5.jpg)

**Comment by lucifering** [comment]
蓝装和金装的名字不做汉化 （蓝装是因为词缀的名字和物品基底结合了，处理比较麻烦就干脆不处理了）
